# Generated by Django 3.1 on 2020-08-30 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='e_contact',
            new_name='econtact',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_email',
            new_name='eemail',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_ei',
            new_name='eid',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='e_name',
            new_name='ename',
        ),
    ]
